---
title: "fig6-topmed"
output: html_document
date: "2025-12-19"
---
---
title: "Fig5-topmed"
output: html_document
date: "2025-12-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
```

```{r}
load("data.RData")
```

```{r}
my_colors <- c("#66c2a5", "#fc8d62", "#8da0cb")


## plotting
my_colors <- c("#66c2a5", "#fc8d62", "#8da0cb")


# known rule boxplots

# Fig 5B EJC downstream
ggplot(data, aes(x = factor(downstream, levels = rev(levels(factor(downstream)))), y = ALLELE.RAT, fill = downstream)) +
geom_boxplot() +
labs(x = "upstream of last EJC") +
#geom_point(shape = 21, alpha = 0.6, colour = "black", fill = "#66c2a5") +
scale_fill_manual(values=my_colors) +
geom_hline(yintercept = 0.5, lty = 2, color = "black", linewidth=0.5) +
theme_bw(base_size=15) +  ylim(0, 1.1)+
theme(axis.text.y   = element_text(size=14),
axis.text.x   = element_text(size=14),
axis.title.y  = element_text(size=14),
axis.title.x  = element_text(size=14),
panel.background = element_blank(),
panel.grid.major = element_blank(),
panel.grid.minor = element_blank(),
axis.line = element_line(colour = "black"),
panel.border = element_rect(colour = "black", fill=NA, linewidth = 1))

#first 200
ggplot(data, aes(x = factor(first.200, levels = rev(levels(factor(first.200)))), y = ALLELE.RAT, fill = first.200)) +
geom_boxplot() +
labs(x = "first 200") +
#geom_point(shape = 21, alpha = 0.6, colour = "black", fill = "#66c2a5") +
scale_fill_manual(values=my_colors) +
geom_hline(yintercept = 0.5, lty = 2, color = "black", linewidth=0.5) +
theme_bw(base_size=15) +  ylim(0, 1.1)+
theme(axis.text.y   = element_text(size=14),
axis.text.x   = element_text(size=14),
axis.title.y  = element_text(size=14),
axis.title.x  = element_text(size=14),
panel.background = element_blank(),
panel.grid.major = element_blank(),
panel.grid.minor = element_blank(),
axis.line = element_line(colour = "black"),
panel.border = element_rect(colour = "black", fill=NA, linewidth = 1))

# long exon
ggplot(data, aes(x = factor(long.exon, levels = rev(levels(factor(long.exon)))), y = ALLELE.RAT, fill = long.exon)) +
geom_boxplot() +
labs(x = "long exon") +
#geom_point(shape = 21, alpha = 0.6, colour = "black", fill = "#66c2a5") +
scale_fill_manual(values=my_colors) +
geom_hline(yintercept = 0.5, lty = 2, color = "black", linewidth=0.5) +
theme_bw(base_size=15) +  ylim(0, 1.1)+
theme(axis.text.y   = element_text(size=14),
axis.text.x   = element_text(size=14),
axis.title.y  = element_text(size=14),
axis.title.x  = element_text(size=14),
panel.background = element_blank(),
panel.grid.major = element_blank(),
panel.grid.minor = element_blank(),
axis.line = element_line(colour = "black"),
panel.border = element_rect(colour = "black", fill=NA, linewidth = 1))

# Fig 5C
ggplot(data, 
       aes(x = relative.position, y = ALLELE.RAT)) + 
 # geom_boxplot(outlier.shape = NA) + 
  geom_point(shape = 21, alpha = 0.6, colour = "black", fill = "#66c2a5") + 
  #scale_color_manual(values = "#66c2a5") +  
  geom_hline(yintercept = 0.5, lty = 2, color = "black", linewidth=0.5) + 
   theme_bw(base_size=15) +  ylim(0, 1.1) + xlim(0, 1) +
 theme(axis.text.y   = element_text(size=14),
        axis.text.x   = element_text(size=14),
        axis.title.y  = element_text(size=14),
        axis.title.x  = element_text(size=14),
        panel.background = element_blank(),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.line = element_line(colour = "black"),
        panel.border = element_rect(colour = "black", fill=NA, linewidth = 1)) +
geom_smooth(method = "loess", se = TRUE, level = 0.95, color = "black") 

# Fig 5E - ejc distance
# penultime exon EJC distance vs. allele ratio
ggplot(data %>% 
         filter(EJC.downstream == 1), 
       aes(x = PTC.2.EJC, y = ALLELE.RAT)) + 
 # geom_boxplot(outlier.shape = NA) + 
  geom_point(shape = 21, alpha = 0.6, colour = "black", fill = "#66c2a5", ) + 
  #scale_color_manual(values = "#66c2a5") +  
  geom_hline(yintercept = 0.5, lty = 2, color = "black", linewidth=0.5) + 
   theme_bw(base_size=15) +  ylim(0, 1.1) + xlim(300, 0) +
 theme(axis.text.y   = element_text(size=14),
        axis.text.x   = element_text(size=14),
        axis.title.y  = element_text(size=14),
        axis.title.x  = element_text(size=14),
        panel.background = element_blank(),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.line = element_line(colour = "black"),
        panel.border = element_rect(colour = "black", fill=NA, linewidth = 1)) +
geom_smooth(method = "loess", se = TRUE, level = 0.95, color = "black") 


# ptc to start distancEs vs. allele ratio
ggplot(data, 
       aes(x = PTC.2.start, y = ALLELE.RAT)) + 
 # geom_boxplot(outlier.shape = NA) + 
  geom_point(shape = 21, alpha = 0.6, colour = "black", fill = "#66c2a5", ) + 
  #scale_color_manual(values = "#66c2a5") +  
  geom_hline(yintercept = 0.5, lty = 2, color = "black", linewidth=0.5) + 
   theme_bw(base_size=15) +  ylim(0, 1.1) + xlim(0, 300) +
 theme(axis.text.y   = element_text(size=14),
        axis.text.x   = element_text(size=14),
        axis.title.y  = element_text(size=14),
        axis.title.x  = element_text(size=14),
        panel.background = element_blank(),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.line = element_line(colour = "black"),
        panel.border = element_rect(colour = "black", fill=NA, linewidth = 1)) +
geom_smooth(method = "loess", se = TRUE, level = 0.95, color = "black") 


```